name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Añade esta línea para dar permisos de escritura
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar MkDocs y dependencias
        run: pip install mkdocs mkdocs-cinder
        #run: pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin

      - name: Desplegar en GitHub Pages
        run: mkdocs gh-deploy --force